### ISSUE TITLE
Pass Widgets and Custom object list in query parameters

### ISSUE THREAD

**Issue by rutaba1** [tomgilder/routemaster#165]
Hi, I want to pass a list of widgets and list of custom models in a new page but query parameters only supports Map<String,String>. With navigator 1.0 it was easy to pass everything directly in navigator like so 
```
Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => DetailScreen(todo: List<TodoModel>),
                ),
              ); 
```
And I also want to do something like this 
```
Navigator.push(
          context,
          PageRouteBuilder(
            opaque: false,
            pageBuilder: (ctx, _, __) {
              return ChangeNotifierProvider(
                  create: (context) => GenericOverlayProvider(),
                  lazy: false,
                  child: overlay);
            },
            transitionDuration: Duration(seconds: 0),
          ));
```
Where I can set opacity of PageRouteBuilder.
 how that would be possible using route master?

**Comment by tomgilder** [comment]
Hi, there's an issue for this already: #96.

Currently it's not possible to pass parameters through any other method than the URL.

I understand the want for this, the problem is making it work with URLs on the web. I'm open to proposals on how to implement this, but I'm really not sure how it would work with Routemaster's URL-centric approach.

Remember you can always still use `Navigator.push()` in conjunction with Routemaster.

Please continue any discussion in the other issue, thanks!
