### ISSUE TITLE
navigator key in routerdelegate

### ISSUE THREAD

**Issue by xoltawn** [tomgilder/routemaster#195]
Hi!
I was wondering why navigator key is not added to routerdelegate?
It can really come in handy where you need context but you don't have access to context directly. for example showing a dialog, etc.
I've added it in my local repository, I can PR if you want

**Comment by tomgilder** [comment]
Hi, can you give an example of how this is useful please? Happy to look at a PR for it too

**Comment by xoltawn** [comment]
for example I'm using Stacked package for the architecture of my app which is based on MVVM architecture.
I display dialogs in ViewModels and I don't have the current context inside viewmodels.so I need to have to access to the current context somehow in order to show dialogs.(or even other widgets)

**Comment by tomgilder** [comment]
Does this use global keys to get the context? As I say, happy to look at a PR, but I'm still not sure exactly what you're proposing 😁

**Comment by xoltawn** [comment]
yes. in MaterialApp widget there is a navigatorKey which we can use to to access the current context, so we don't need to pass context around inside or View. I'm suggesting to add this capability  since MaterialApp.router() doesn't have this property. I will send  a PR tommorrow .

**Comment by DusBekas** [comment]
> yes. in MaterialApp widget there is a navigatorKey which we can use to to access the current context no matter which widget we're in, so we don't need to pass context around from our View. I'm suggesting to add this capability since MaterialApp.router() doesn't have this property. I will send a PR tomorrow .

I believe you are referring to navigate without context?

I have difficulties too with this one. Since I'm not quite get the example here [https://pub.dev/packages/routemaster#navigate-without-a-context](url) 

😁

**Comment by BazinC** [comment]
@tomgilder in my scenario I use `modal_bottom_sheet` package in order to use `showMaterialModalBottomSheet` and show nice bottom sheets powered by a scroll controller.
Your example '**mobile_app**' use `modal_bottom_sheet` but it is not possible to scroll the content down to dismiss the modal page.

We need a way to retrieve Navigator key (or navigator context) and pass it to showBottomSheet-like methods who needs a navigator. Sometimes these calls are made outside the Navigator scope (e.g with ViewModels outside the MaterialApp).

I like @xoltawn PR proposal. Could you please take a look? :)🙏

**Comment by tomgilder** [comment]
Done!
