### ISSUE TITLE
How to push a new route onto a CupertinoTabView?

### ISSUE THREAD

**Issue by sunndog** [tomgilder/routemaster#71]
Rather than pushing a page onto the page containing the CupertinoTabScaffold, I want to push a page to the Navigator of the CupertinoTabView.  It's unclear to me if that's possible.  thanks.

**Comment by tomgilder** [comment]
Hey, it's not possible to use `CupertinoTabView` itself because it doesn't support Navigator 2.0 - in that it doesn't have a `pages` property.

But `CupertinoTabView` doesn't really do anything special, you can achieve the all the same things without it.

Both simple_example and mobile_app show how to set up Cupertino tabs:
https://github.com/tomgilder/routemaster/blob/main/example/simple_example/lib/main.dart
https://github.com/tomgilder/routemaster/blob/main/example/mobile_app/lib/main.dart

Let me know if you have any more questions.

**Comment by sunndog** [comment]
Assuming this [new feature request](https://github.com/flutter/flutter/issues/83039) was to be addressed in Flutter... would it be possible to make routemaster route into several pages within a CupertinoTabView?
