### ISSUE TITLE
Add documentation to all methods and classes

### ISSUE THREAD

**Issue by tomgilder** [tomgilder/routemaster#73]

**Comment by rydmike** [comment]
Big YES to this one please! 😄 

I know documentation is a big drag, but I was looking cluelessly at some of the public APIs, since most have no docs and I feel they do need explanations on what they do and in many cases some mention/example of what scenarios you should use them in.

Without the current nice samples it would not be possible to get very far, unless you spend time and really go through all the lovely code of course.

Think of this as your fabulous and impressive tests, the number should be >98% 💙 
![image](https://user-images.githubusercontent.com/39990307/117568492-350ea780-b0c9-11eb-9799-9cd67dd1759a.png)


There is also a lint that you should turn on for package that complains if any public API is missing a doc comment. Very handy for public packages since the lovely analyzer then bickers about it until you add doc comments to all public APIs.

---

**SIDENOTE**
Curiously the lint will not find all places where you need to add a doc comment. In my packages I noticed pub.dev still claims 1-3 APIs don't have doc comments, despite the lint, the analyzer does not find any, nor can I find which ones they would be. I was going for 100% doc comments, but have not been able to get there. So I concluded never mind about the missing 2-3 that pub.dev claims is there. 😃
