### ISSUE TITLE
Scenario: popping multiple pages

### ISSUE THREAD

**Issue by tomgilder** [tomgilder/routemaster#75]
Pages A, B and C are on the navigation stack. User is on page C at path `/a/b/c`.

We want to pop back to page A... how? Answer: `push('/a')` - but that feels weird. 

From a user's perspective, it feels like you want to call `popTo('/a')`.

Needs documentation and/or better API.

**Comment by tomgilder** [comment]
Is `push()` actually the wrong name for `push()`? Should it be `navigate()`? I don't _think_ so

**Comment by rydmike** [comment]
Perhaps docs plus examples is all that is needed. 

It does feels a bit  un-intuitive at first to just push a new route, if you think of it strictly as a stack. On mobile you would after a `popTo('/a')` expect that (Android) system back no longer takes you back to `/a/b/c`, since there would be only `/a` left on the stack and maybe `/` left to pop further to. But if you do a `push('/a')` that if you then hit system back you would be back at `/a/b/c`. Then again with web and browser back button, you expect it retain the browser back history regardless of if you push, popTo, naviagteTo '/a'. 

I've been struggling with what to do with these navigation patterns in multi platform Flutter apps as well.

**Comment by tomgilder** [comment]
I guess this is fundamentally a trade-off between API familiarity and usability. I'd say this is also a fairly unusual use case, generally when popping it's just going back one. I _really_ don't want to get in to `pop(2)` 😁

**Comment by tomgilder** [comment]
I don't think there's anything that can be done here API-wise.

Added an FAQ here, will think if I can add anything to the documentation: https://github.com/tomgilder/routemaster/wiki/FAQs

**Comment by rydmike** [comment]
I agree, my comment was intended to mean that the API is imo fine. It only needs documentation. You could also add what you wrote in the FAQ to the API docs for push as well, as one more use case for it.

**Comment by EdsonBueno** [comment]
Hi @tomgilder.
By using `push` instead of `popUntil` we open a "fresh" instance of the page instead of going back to the old one. Is that right?
Isn't it the same as saying we don't need a `pop` function because we can always use a `push` or `replace` to the previous route?

**Comment by tomgilder** [comment]
@EdsonBueno good point, hadn't thought of that use case 😁

**Comment by tomgilder** [comment]
`popUntil` added, will be in v0.10 - let me know if there are any more wants for additional APIs for this

**Comment by EdsonBueno** [comment]
Thanks @tomgilder !
